FROM node:10 AS build

COPY web /app/web
RUN cd /app/web \
    && npm install \
    && npm run build \
    && npm cache clean --force

FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.8

COPY requirements.txt /app/requirements.txt
RUN pip --no-cache-dir install -r /app/requirements.txt
COPY --from=build /app/web/build /app/build

COPY app.py /app/app.py
COPY config.py /app/config.py
COPY uwsgi.ini /app/uwsgi.ini
COPY emustrings /app/emustrings

