FROM python:3.6-alpine

COPY requirements.txt /app/requirements.txt
RUN pip --no-cache-dir install -r /app/requirements.txt

COPY daemon.py /app/daemon.py
COPY config.py /app/config.py
COPY emustrings /app/emustrings

WORKDIR /app/
ENTRYPOINT celery worker -A daemon
